# Only use pps as time source, recieve it over socket
refclock SOCK /run/chrony.pps1.sock refid PPS precision 1e-7

# Fallback NTP servers (cellular connection)
pool pool.ntp.org iburst

# Allow fast initial sync
makestep 1.0 3

# RTC drift file
driftfile /var/lib/chrony/drift

# Log tracking
logdir /var/log/chrony
log tracking measurements statistics
