<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>tanker_vision</name>
  <version>0.0.0</version>
  <description>All custom nodes to achieve tanker vision</description>
  <maintainer email="trail@todo.todo">trail</maintainer>
  <license>TODO: License declaration</license>
  
  <!-- Use ament_python as the build tool for a Python package -->
  <buildtool_depend>ament_python</buildtool_depend>

  <!-- If you do NOT generate custom messages, you can remove rosidl_default_generators.
       If you do generate custom messages, keep it and also add the necessary steps
       in a CMakeLists.txt or in your setup.py for message generation. -->
  <!-- <buildtool_depend>rosidl_default_generators</buildtool_depend> -->

  <!-- Runtime dependencies -->
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>cv_bridge</depend>
  <exec_depend>v4l2_camera</exec_depend>
  <exec_depend>topic_tools</exec_depend>
  <!-- Add any other needed dependencies here -->

  <!-- Test dependencies -->
  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <!-- Indicate that this is a Python package -->
    <build_type>ament_python</build_type>
  </export>
</package>
