im19_mems_node:
  ros__parameters:
    port: /dev/im19_mems
    baud: 115200
    timeout: 0.05
    frame_id: im19
    output_dir: /mnt/storage
    chunk_size: 1024

    stats_period_sec: 300.0
    flush_period_sec: 5.0
    reconnect_period_sec: 1.0

    send_startup_commands: true
    startup_commands:
      - "AT+MEMS_OUTPUT=UART1,ON"
      - "AT+NAVI_OUTPUT=UART1,ON"
      - "AT+NASC_OUTPUT=UART1,OFF"
      - "AT+AHRS=ENABLE"
      - "AT+INSTALL_ANGLE=180,0,90"
      - "AT+WORK_MODE=13"
      - "AT+LEVER_ARM2=0.10195,0.00,0.03"


    rotate_every_mb: 200
    rotate_every_sec: 1800
