# tankervision.yaml — Unique Configuration for Each Flight Computer.
# Change 'mode' before each flight.

mode: testing

unit:
  name: argus
  plane_number: BD-122
  city: Prince George
  province: British Columbia
