# tankervision.yaml — Global configuration for TankerVision flight computer.
# Change 'mode' before each flight.

mode: testing

unit:
  name: argus
  plane_number: BD-122
  province: British Columbia

notifications:
  email_to: wildfire@robotics.utias.utoronto.ca
  gmail_user: wildfire@robotics.utias.utoronto.ca
  gmail_app_password: aqszpdqdypwqrkre
  

storage:
  root: /mnt/storage
  saved_frames_dir: /mnt/storage/saved_frames

trigger:
  topic: /save_images_trigger
  timeout_sec: 20
  cooldown_sec: 5

lucid_camera:
  topic: /cam0/image_raw
  width: 5320
  height: 4600
  exposure_time: 3000.0
  pixelformat: bayer_rggb16
  qos_reliability: reliable

analog_camera:
  topic: /cam1/image_raw
  device: /dev/video0
  standard: NTSC
  ntsc:
    image_size: [720, 480]
    time_per_frame: [1001, 30000]
  pal:
    image_size: [720, 576]
    time_per_frame: [1, 25]

ptp:
  interface: auto
  require_sync_before_launch: true
