# tankervision.yaml — System Configuration for Each Flight Computer.

#hardware_trigger: false | true | on_pps

notifications:
  email_to: wildfire@robotics.utias.utoronto.ca
  gmail_user: wildfire@robotics.utias.utoronto.ca
  gmail_app_password: aqszpdqdypwqrkre
  
# manage: true to enable cellular on/off control
# takeoff_delay: 300  = turn off 300 seconds after node starts (regardless of flight state)
#                'in_air' = turn off when speed >14m/s detected
cellular:
  manage: true
  #at_port: /dev/ttyUSB5  # optional — auto-detected from ttyUSB ports if not set
  takeoff_delay: in_air

storage:
  root: /mnt/storage
  saved_frames_dir: /mnt/storage/saved_frames

trigger:
  topic: /save_images_trigger
  timeout_sec: 20

lucid_camera:
  topic: /cam0/image_raw
  width: 5320
  height: 4600
  hardware_trigger: on_pps
  pixelformat: bayer_rggb16
  bayer_raw_shift: 8
  publish_downscale_factor: 8
  acquisition_frame_rate_enable: true
  acquisition_frame_rate: 1.0
  qos_reliability: reliable

analog_camera:
  topic: /cam1/image_raw
  device: /dev/video0
  standard: NTSC
  ntsc:
    image_size: [720, 480]
    time_per_frame: [1001, 30000]
  pal:
    image_size: [720, 576]
    time_per_frame: [1, 25]

#dominance ration:  B must be this many times > R and G to be "blue"
#threshold: minimum mean B value before ratio check applies
maxvis_recording:
  blue_dominance_ratio: 1.5   
  blue_mean_threshold: 80
  record_fps: 1.0

yolo:
  model: src/tanker_vision/tanker_vision/base_yolo.pt
  target_class: 10
  confidence: 0.3
 
ptp:
  interface: auto
  require_sync_before_launch: true

gpsd_velocity:
  publish_rate_hz: 1.0

velocity:
  takeoff_threshold_m_s: 5.0
  landing_threshold_m_s: 0.5
