[global]
twoStepFlag             1
slaveOnly               0
priority1               128
priority2               128
domainNumber            0
clockClass              135
clockAccuracy           0x31
offsetScaledLogVariance 0xffff
logAnnounceInterval     1
logSyncInterval         0
logMinDelayReqInterval  0
announceReceiptTimeout  3
transportSpecific       0x0
network_transport       UDPv4
delay_mechanism         E2E
time_stamping           software

[eno1]
