#!/bin/bash
# setup_msmtp.sh — Configure msmtp for Gmail on this flight unit.
# Run once per machine during initial setup (called by install.sh).
#
# Reads gmail_user and gmail_app_password from tankervision.yaml.
# Usage: sudo bash setup_msmtp.sh [path/to/tankervision.yaml]

set -e
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()  { echo -e "${GREEN}[msmtp]${NC} $*"; }
warn()  { echo -e "${YELLOW}[msmtp]${NC} $*"; }
error() { echo -e "${RED}[msmtp]${NC} $*"; exit 1; }

[[ $EUID -ne 0 ]] && error "Run as root: sudo bash setup_msmtp.sh"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
YAML="${1:-$SCRIPT_DIR/../config/tankervision.yaml}"
[[ -f "$YAML" ]] || error "Config not found: $YAML"

# Parse gmail credentials from YAML
GMAIL_USER=$(python3 -c "
import yaml, sys
with open('$YAML') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('notifications', {}).get('gmail_user', ''))
" 2>/dev/null)

GMAIL_PASS=$(python3 -c "
import yaml, sys
with open('$YAML') as f:
    cfg = yaml.safe_load(f)
print(cfg.get('notifications', {}).get('gmail_app_password', ''))
" 2>/dev/null)

[[ -z "$GMAIL_USER" ]]  && error "notifications.gmail_user not set in $YAML"
[[ -z "$GMAIL_PASS" ]]  && error "notifications.gmail_app_password not set in $YAML"

# Determine the non-root user to configure for
TARGET_USER="${SUDO_USER:-$(logname 2>/dev/null || echo trail)}"
HOME_DIR=$(eval echo "~$TARGET_USER")

# Write msmtprc
MSMTPRC="$HOME_DIR/.msmtprc"
cat > "$MSMTPRC" << MSMTP
# msmtp config — generated by setup_msmtp.sh
defaults
  auth           on
  tls            on
  tls_trust_file /etc/ssl/certs/ca-certificates.crt
  logfile        $HOME_DIR/.msmtp.log

account        gmail
host           smtp.gmail.com
port           587
from           $GMAIL_USER
user           $GMAIL_USER
password       $GMAIL_PASS

account default : gmail
MSMTP

chmod 600 "$MSMTPRC"
chown "$TARGET_USER:$TARGET_USER" "$MSMTPRC"
info "Written $MSMTPRC"

# Test the config
info "Testing connection to smtp.gmail.com..."
if sudo -u "$TARGET_USER" msmtp --serverinfo --account=gmail &>/dev/null; then
    info "msmtp configured successfully for $GMAIL_USER"
else
    warn "msmtp serverinfo test failed — check credentials and Gmail app password"
    warn "Make sure 2FA is enabled and app password was generated at myaccount.google.com"
fi